"""empty message

Revision ID: 077a6f167f50
Revises: 
Create Date: 2018-03-05 12:20:27.983460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '077a6f167f50'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('password', sa.String(length=60), nullable=True),
    sa.Column('email', sa.String(length=254), server_default='', nullable=False),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
